### ISSUE TITLE
write dataid

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#1]
https://github.com/dbpedia/data-release-tool-ti/blob/master/databusmavenplugin/src/main/scala/org/dbepdia/databus/FileAnalysis.scala#L114

I created a stub for the dataid generation
Note that:
* data files are copied to /target/classes during a later phase. if you run `databus:analysis` then the folder is not yet created
* we still need to discuss, whether we have one dataid file per file or just one.... at the moment just one also seems ok, but for development it might be easier to just have one dataid for each datafile

**Comment by kurzum** [comment]
move to external class: https://github.com/dbpedia/data-release-tool-ti/blob/master/databusmavenplugin/src/main/scala/org/dbpedia/databus/voc/DataFileToModel.scala

**Comment by Termilion** [comment]
*Update:*
- All Contents from the Example-DataId are now generated.
- Added necessary Configuration Variables in the pom.xml
- Added generation of the MediaType from the MimeType using the same method from the extraction-framework-script
- are we using authorizations? if yes → TODO
```
<http://dbpedia.org/dataset/pages_articles?lang=de&dbpv=2016-10&auth=publisherAuthorization>
        a                          dataid:Authorization ;
        dataid:authorityAgentRole  dataid:Publisher ;
        dataid:authorizedAgent     <https://wikimediafoundation.org> ;
        dataid:authorizedFor       <http://dbpedia.org/dataset/pages_articles?lang=de&dbpv=2016-10> ;
        dataid:isInheritable       true .
```
- the schema is hardcoded for now: if ontology is changed → code needs to be changed, too.
  ⇒ TODO: find a smooth way to do this dynamically

**Comment by kurzum** [comment]
closed, will create a new one with leftovers
