### ISSUE TITLE
document issued and modifieddate generation

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#10]
https://github.com/dbpedia/databus-maven-plugin/blob/master/archetype/existing-project/bundle/pom.xml#L110

* These two might be automatically generated, so implement it
* need documentation

**Comment by Termilion** [comment]
creation date and modification date are easily implementable with JDK7: https://docs.oracle.com/javase/7/docs/api/java/nio/file/attribute/BasicFileAttributeView.html
but not all file systems support creation date: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Metadata
I wrote a small implementation for the modification date.

**Comment by neradis** [comment]
Implementation is in place an as follows:
For modification date, use the value provided in the build property `databus.modifiedDate` if defined, else use the last the last modified time according to the filesystem.
For issued date, use the value provided in the build property `databus.issuedDate` if defined, else use the invocation time of the `mvn`-build.

Documentation of this behaviour is still to be done.

**Comment by kurzum** [comment]
moved to User Manual https://github.com/dbpedia/databus-maven-plugin/wiki
