### ISSUE TITLE
content variant dropdown not scrollable/readable

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#106]
as the screenshot shows i can not scroll and read the remaining content variants in collection editor since it is cut off at the bottom. 

- [x] can this be fixed?

- [x]  It would also really make sense to exclude entries in this list which have been already checked, right?

![image](https://user-images.githubusercontent.com/2630603/72927937-65f18e80-3d57-11ea-8b58-c67aedcec151.png)

**Comment by holycrab13** [comment]
removed already added facets from dropdown

**Comment by JJ-Author** [comment]
looks good.
