### ISSUE TITLE
Cannot add newly uploaded dataset to collection - artifact or group does not show up in collection editor search

### ISSUE THREAD

**Issue by HeikoPaulheim** [dbpedia/databus-maven-plugin#108]
Hi,

we’ve just added CaLiGraph to the DBpedia Databus (yay!):
https://databus.dbpedia.org/nheist/CaLiGraph/

Now, I’ve tried creating a collection for a combined version of DBpedia and CaLiGraph, but CaLiGraph is not visible when I try to add it to the collection.

I’ve clicked on “Generated Queries” and tried various search terms, but it can’t be found.

Is there some caching/indexing in the background so that it takes a while before a newly uploaded dataset can be added to a collection? Or do I get something else wrong here?

Thanks,
Heiko

**Comment by JJ-Author** [comment]
Hey Heiko,
I also stumpled upon this problem before. Yes the lucene index is updated on a batch basis. Dynamic updates of the index are on todo list. For the moment there is a workaround. Just go to your databus profile and pick one artifact(s) (dataset) of interest (in your case e.g. https://databus.dbpedia.org/nheist/CaLiGraph/instances-types/) and then add to collection in the left bottom. I agree that is annoying if you would like to only add the entire group. so I will open some issues w.r.t.

p.s. you can also wait some days until the index is updatet if it is not too urgent.

**Comment by JJ-Author** [comment]
opened #110 and #111

**Comment by holycrab13** [comment]
Created a mechanism to index newly added content. This check is done every minute, so it should show up in the search much faster.
