### ISSUE TITLE
unable to find dbpedia mappings geo-coordinates

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#114]
I created a collection with marvin/mappings/geo-coordinates:
https://databus.dbpedia.org/kurzum/collections/databus-demo

but actually I would like to have dbpedia/mappings/geo-coordinates but it doesn't show up in search:

![Screenshot from 2020-02-19 13-34-31](https://user-images.githubusercontent.com/900758/74834889-9871b580-531c-11ea-94ad-5f9d9083e67a.png)

**Comment by JJ-Author** [comment]
the entire mappings group seems not indexed at the moment

**Comment by holycrab13** [comment]
This was an error in the indexing!
searching "dbpedia mappings geo-coordinates" will show the desired result

**Comment by holycrab13** [comment]
Is this issue still up to date?
https://databus.dbpedia.org/dbpedia/mappings/geo-coordinates doesn't seem to be an artifact.

**Comment by kurzum** [comment]
Works fine, thx
