### ISSUE TITLE
collection stats seem not to work

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#117]
`Failed to load collection statistics. Make sure the collection is published and try again.`

https://databus.dbpedia.org/dbpedia/collections/latest-core/

**Comment by holycrab13** [comment]
statistics changed to summary, which is now working

**Comment by JJ-Author** [comment]
are the statistics problematic? it was actually quite good to see the license and number of files / filesize

**Comment by holycrab13** [comment]
Summary displays the exact same thing, just labelled differently.

**Comment by JJ-Author** [comment]
ah ok sry i got confused because the tab was missing. i liked the integration in the tab view more, but this is really personal opinion. so great work.
