### ISSUE TITLE
Cannot login to Databus using GitHub

### ISSUE THREAD

**Issue by KonradHoeffner** [dbpedia/databus-maven-plugin#119]
I want to post on the DBpedia forum but when I try to login using GitHub, I get the message "We're sorry...Unexpected error when authenticating with identity provider".
It seems to be a server issue but just in case, I tried it with both Firefox Developer Edition 75.0b11 (64-bit) and with Chromium 80.0.3987.163.

**Comment by holycrab13** [comment]
Hi Konrad,
can you try again? There was an error in the configuration that is fixed now. Hope it resolves this issue.

**Comment by KonradHoeffner** [comment]
It works now and it even auto-links to the account I had created manually, great feature!
