### ISSUE TITLE
issues with collections

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#120]
Tested https://databus.dbpedia.org/dbpedia/collections/latest-core

Issue 1:
Filesize is not calculated properly, i.e.  64025.39 MB  and the individual fies are also displayed as too large. I guess this is a small glitch

Issue 2:
I have pushed 2020.04.01 on the bus for mappings and generic. But the collection still diplays the 2020.03.01 version. This makes me worried, because it seems as if the collection is static, i.e. materialized, although it should be queried dynamically.

**Comment by holycrab13** [comment]
Both seem to be a UI issue, the collection query fetches the correct data.
Also both are related to server-side caching that causes the data overview to not update correctly. 
I will have a look!

**Comment by JJ-Author** [comment]
problem with custom query collections. e.g curl https://databus.dbpedia.org/jfrey/collections/onto-paper-oops -H "accept: text/sparql"

- [x] curl:  Unable to find the collection

- [x] UI: custom query is not shown in user collection view (hierarchy tab)
- [x] UI: stats are not calculated correctly (summary and data)

**Comment by holycrab13** [comment]
Issue should be fixed

**Comment by kurzum** [comment]
ok, from my side, but @JJ-Author hi-jacked the issue and added more stuff, so he should close.

**Comment by JJ-Author** [comment]
yes is looking great.
