### ISSUE TITLE
collection IRI of user A (actually does not exist) retrieves collection of user B

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#121]
see https://databus.dbpedia.org/dbpedia/collections/onto-paper-oops/
is this intended?

**Comment by JJ-Author** [comment]
![image](https://user-images.githubusercontent.com/2630603/81535318-e15c6780-9369-11ea-814c-db470fe779ab.png)

**Comment by JJ-Author** [comment]
probably a caching issue? because sometimes it shows my collection sometimes it shows collection was not found.

**Comment by holycrab13** [comment]
Was related to bad caching indeed, should be fixed.

**Comment by JJ-Author** [comment]
yes :-)
