### ISSUE TITLE
Collection displays error, if more than 6 language tags are selected

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#124]
( @holycrab13 this is not a crucial feature. Fixing can be done after the tutorial) 
Reproduce:
I added multilingual labels, abstracts to https://databus.dbpedia.org/dbpedia/collections/latest-core
These should consist of the following languages: `ar de es fr it ja nl pl pt ru zh` 
Upon adding the seventh tag in the UI, there is an Error displayed: 

![Screenshot from 2020-06-24 18-18-37](https://user-images.githubusercontent.com/900758/85593278-2fda7280-b647-11ea-8587-39ac14d50962.png)

**Comment by holycrab13** [comment]
[this is the error](https://databus.dbpedia.org/repo/sparql?query=PREFIX%20dataid%3A%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcore%23%3E%0APREFIX%20dataid-cv%3A%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23%3E%0APREFIX%20dct%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20dcat%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0A%0A%23%20Get%20all%20files%0ASELECT%20DISTINCT%20%3Ffile%20%3Fversion%20(GROUP_CONCAT(DISTINCT%20%3Fvar%3B%20SEPARATOR%3D%27%2C%20%27)%20AS%20%3Fvariant)%20%3Fformat%20%3Fcompression%20%3Fsize%20%3Fpreview%20WHERE%20%7B%0A%20%09%3Fdataset%20dataid%3Aartifact%20%3Chttps%3A%2F%2Fdatabus.dbpedia.org%2Fdbpedia%2Fmappings%2Fmappingbased-literals%3E%20.%0A%09%3Fdataset%20dcat%3Adistribution%20%3Fdistribution%20.%09%3Fdistribution%20dct%3AhasVersion%20%3Fversion%20.%09%3Fdistribution%20dataid%3AformatExtension%20%3Fformat%20.%09OPTIONAL%20%7B%20%3Fdistribution%20dataid%3AcontentVariant%20%3Fvar%20.%20%7D%09%3Fdistribution%20dataid%3Acompression%20%3Fcompression%20.%09%3Fdistribution%20dcat%3AbyteSize%20%3Fsize%20.%09%3Fdistribution%20dataid%3Apreview%20%3Fpreview%20.%0A%09%7B%0A%09%09%3Fdistribution%20dct%3AhasVersion%20%3FlatestVersion%20%0A%09%09%7B%0A%09%09%09SELECT%20(%3Fversion%20as%20%3FlatestVersion)%20WHERE%20%7B%20%0A%09%09%09%09%3Fdataset%20dataid%3Aartifact%20%3Chttps%3A%2F%2Fdatabus.dbpedia.org%2Fdbpedia%2Fmappings%2Fmappingbased-literals%3E%20.%20%0A%09%09%09%09%3Fdataset%20dct%3AhasVersion%20%3Fversion%20.%20%0A%09%09%09%7D%20ORDER%20BY%20DESC%20(%3Fversion)%20LIMIT%201%20%0A%09%09%7D%20%0A%09%7D%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27en%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27be%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27az%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27ar%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27bn%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27cs%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27cy%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27bg%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09UNION%0A%09%7B%20%0A%09%09%3Fdistribution%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcv%23lang%3E%20%27de%27%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%20%0A%09%7D%20%0A%09%3Fdistribution%20dcat%3AdownloadURL%20%3Ffile%20.%0A%7D%20GROUP%20BY%20%3Ffile%20%3Fversion%20%3Fformat%20%3Fcompression%20%3Fsize%20%3Fpreview&callback=jQuery341008980736232716491_1593681505738&format=json&_=1593681505744) 

Virtuoso 42000 Error SQ200: The memory pool size 400015360 reached the limit 400000000 bytes, try to increase the MaxMemPoolSize ini setting.

Obvious fix would be increasing the memory pool size, but with these large auto-generated queries this might become an issue again
