### ISSUE TITLE
establish a best practice for resource closing

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#14]
inputstream is opened with Datafile.getInputstream
However, these need to be closed consistently across the plugin, ideally using the same type of code, 
Could you make an example?

**Comment by neradis** [comment]
I suggest thorough usage of [Scala ARM](http://jsuereth.com/scala-arm/usage.html) for such cases.
The basic idea that resources that need  cleanup (like the closing of an InputStream) are encapsulated in `ManagedResource` instances, that receive instructions how to construct/open the resource and to close it after an operations on them completed (be it by successful completion or error).
It's about seperating the concerns of the lifecycle management for the resource (then handleded by the aforementions `ManagedResource` wrapper and defining what is supposed to happen with the resource. The latter is done by using functional operations like `map`, `flatMap`, `and` (akin to `zip`) etc.

https://github.com/dbpedia/databus-maven-plugin/blob/14de2ff02bfa147ad25898bfc9f9495adaa74c07/src/main/scala/org/dbpedia/databus/TestData.scala#L74-L77 shows an example of the most basic usage of just defining one set of operation to be done on the managed InputStream (read as 'what would go into the `try` block in Java)

https://github.com/dbpedia/databus-maven-plugin/blob/14de2ff02bfa147ad25898bfc9f9495adaa74c07/src/main/scala/org/dbpedia/databus/lib/Datafile.scala#L110-L115 illustrated a simple monadic use case: We derive a `Source` object from the managed `InputStream`, after the operations in the body of the `for` close, both with be closed.
