### ISSUE TITLE
Lack of self-description of generated DataId-documents

### ISSUE THREAD

**Issue by neradis** [dbpedia/databus-maven-plugin#19]
Currently, the generated DataID documents do not generate a `dataid:DataId` resource that states who are agents having the `dataid:Maintainer` or `dataid:Publisher` agent role, for the DataId itself (which, in particular would mean that they are allowed to update the DataId (`dataid:UpdateDataId`). 

Also, without such resource, from the DataId consumer perspective, this means it's not conclusively clear who published the DataId and whom to contact about it (as the maintainer of the DataId-metadata is not necessarily the same as the one for the data described.)

**Comment by kurzum** [comment]
My comment here:
while we need a DataId node to describe the dataid file, I think it is not necessary to encode any ACLs into it. The main purpose of this node is to advertise the Databus Maven Plugin, i.e. generated with....

So the node should probably contain the publisher information,  license being public domain, a clear explanation that this is the dataid node and that the license refers to the metadata and not the data. 

I put the generation of a signature for the dataid in another issue. 
@Termilion I already implemented some stuff in prepareMetadata and you could add something like this: 
```
<> a foaf:PersonalProfileDocument ;
   foaf:maker <#this> ;
   foaf:primaryTopic <#this> .

<#this> a foaf:Person ;
```
Note that there is code resolving the relative dataid to the uris of deployment already. This is actually done in package-export with: 
```
 dataIdCollect.read(getDataIdFile().toURI.toString,downloadUrlPath.toString+getDataIdFile.getName,"turtle")

```
