### ISSUE TITLE
fix artifact IRIs and rename dataids. 

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#29]
at the moment we have really strange IRIs for artifacts
https://downloads.dbpedia.org/repo/lts/generic-spark/article-templates/2018.10.16/article-templates-2018.10.16_dataid.ttl#article-templates-2018.10.16 

it contains the artifact id twice (actually the information is even thrice)
easy but simple fix would be to rename the dataid file to dataid.ttl as it used to be before.

**Comment by kurzum** [comment]
@JJ-Author there are new short URIs now assigned via DBpedia accounts. Hence, this issue can be closed imho.

**Comment by kurzum** [comment]
<https://downloads.dbpedia.org/repo/lts/generic-spark/article-templates/2018.10.16/dataid.ttl#Dataset>
<https://downloads.dbpedia.org/repo/lts/generic-spark/article-templates/2018.10.16/dataid.ttl#article-templates-2018.10.16_plwiki.ttl.bz2>
