### ISSUE TITLE
openssl command for DER/PKCS8 format in readme.md

### ISSUE THREAD

**Issue by yum-yab** [dbpedia/databus-maven-plugin#31]
This should be written somewhere in the readme:

Note that Java/Scala only accepts DER/PKCS8 formatted files, so you might need to run:
$ openssl pkcs8 -topk8 -inform PEM -outform DER -in private_key.pem -out private_key.der -nocrypt
We recommend putting the file in ~/.m2 next to the settings.xml (Maven user dir):
```
<privateKeyFile>${user.home}/.m2/private_key.der</privateKeyFile>
```
SECURITY NOTICE:
* Protect your private key file, do not loose, do not send over network
* chmod 700
* The data channel you are about to create requires it to republish new versions there.

**Comment by kurzum** [comment]
.pfx works as generated by the webid script

Issue here is to update the WebID docu

**Comment by kurzum** [comment]
Added in code and user manual: https://github.com/dbpedia/databus-maven-plugin/wiki/User-Manual-v1.3#pkcs12file
