### ISSUE TITLE
version number is duplicated if already present in filename

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#36]

**Comment by Vehnem** [comment]
E.g duplicated in: http://downloads.dbpedia.org/repo/dev/dbpedia-diff/labels-diff/2018.11.03/ and http://downloads.dbpedia.org/repo/dev/fusion/fused-geo-coordinates/2018.11.25/

As it should be in: http://downloads.dbpedia.org/repo/dev/mappings/instance-types/2018.11.03/

**Comment by neradis** [comment]
A solution is introduced in [branch fix-issue-36](https://github.com/dbpedia/databus-maven-plugin/tree/fix-issue-36) ( 8368d6d). A switch (`datbus.insertVersion`) is introduced that allows to switch off that the plugin inserts the version on package-export. (e.g. if the input files themselves already contain a version part, as for the diffs and fusion results).
