### ISSUE TITLE
implement mvn databus:update-rss

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#4]
I already tested the rome library https://rometools.github.io/rome/
it produces RDF using `feed.setFeedType("rss_1.0")`

# Workflow is like this:
## init
config option `feed` gives the existing feed file. This can be a URL or a local file. Initially the feedfile can be configured by hand, see template below. later after the first publishing it can be the url 
e.g. `http://78.46.100.7/wikidata/` + feed.xml
## add
so once the feed is published, it can be retrieved, loaded. Small check whether the dataset version is already in it, e.g. compare artifactid and version number. If it is not add it and generate the new feed.xml file into `target`. Convention will be that there is a folder `target/databus/$artifactId/$version` and the feed is under `target/$artifactid/feed.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel rdf:about="http://www.bbc.co.uk/music/reviews/latest">
    <title>Latest Reviews</title>
    <link>http://www.bbc.co.uk/music/reviews/latest</link>
    <description>These are the latest reviews recommended on BBC Music</description>
    <dc:subject>BBC Music</dc:subject>
    <dc:language>en-en</dc:language>
    <dc:rights>Copyright: (C) British Broadcasting Corporation</dc:rights>
  </channel>
</rdf:RDF>
```
entries can be added later by rome:
```
val feedUrl = new URL("http://www.bbc.co.uk/feeds/rss/music/latest_releases.xml")
    val input = new SyndFeedInput
    val feed = input.build(new InputStreamReader(feedUrl.openStream))
    val types: List[String] = List("rss_0.9", "rss_0.91", "rss_0.92", "rss_0.93", "rss_0.94", "rss_1.0", "rss_2.0", "atom_0.3")
    feed.setFeedType(types.apply(5))
    var entries: util.ArrayList[SyndEntry] = new util.ArrayList[SyndEntry]()
    var entry: SyndEntry = new SyndEntryImpl()
    entry.setTitle("Rome v1.0")
    entry.setLink("http://wiki.java.net/bin/view/Javawsxml/Rome01")
    //entry.setPublishedDate(DATE_PARSER.parse("2004-06-08"))
    var description: SyndContent = new SyndContentImpl()
    description.setType("text/plain")
    description.setValue("Initial release of Rome")
    entry.setDescription(description)
    entries.add(entry)
    entry = new SyndEntryImpl()
    entry.setTitle("Rome v3.0")
    entry.setLink("http://wiki.java.net/bin/view/Javawsxml/Rome03")
    //entry.setPublishedDate(DATE_PARSER.parse("2004-07-27"))
    description = new SyndContentImpl()
    description.setType("text/html")
    description.setValue("<p>More Bug fixes, mor API changes, some new features and some Unit testing</p>" +
      "<p>For details check the <a href=\"http://wiki.java.net/bin/view/Javawsxml/RomeChangesLog#RomeV03\">Changes Log</a></p>")
    entry.setDescription(description)
    entries.add(entry)
    feed.setEntries(entries)

    val output = new SyndFeedOutput
    output.output(feed, new FileWriter("/tmp/test.xml"))
```

**Comment by Vehnem** [comment]
I can not determine which entries the generated rss feed files should contain. So i need to discuss the entries. I wrote an example, how i think it should look.

`<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">    <channel rdf:about="http://78.46.100.7/wikidata/feed.xml"> // dataid_catalog?        <title>DBpedia ontology based wikidata extraction</title>        <link>http://78.46.100.7/wikidata/feed.xml</link>        <description>These are the latest wikidata.dbpedia.org releases</description>        <items>            <rdf:Seq>                <rdf:li rdf:resource="http://78.46.100.7/wikidata/artifactid/version/dataid.ttl" />            </rdf:Seq>        </items>        <dc:subject>Databus</dc:subject>        <dc:language>en-en</dc:language>        <dc:rights>http://purl.oclc.org/NET/rdflicense/cc-by-sa3.0</dc:rights>    </channel>    <item rdf:about="http://78.46.100.7/wikidata/artificatid/version/dataid.ttl">        <title>wikidata 2018-01-01</title>        <link>http://78.46.100.7/wikidata/artifactid/version/dataid.ttl</link> // dataid for each file ?        <description>Initial release</description>        <dc:date>2018-01-02T22:00:00Z</dc:date> // modifier, issue, or entry date?        <author>http://kurzum.net/dev-dummy.ttl#this</author> // webid    </item></rdf:RDF>`
