### ISSUE TITLE
Display issue tracker link

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#57]
display where to add bugs and features on every page

**Comment by kurzum** [comment]
Link:
https://github.com/dbpedia/databus-maven-plugin/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite

**Comment by holycrab13** [comment]
Added a link in both footer and header

**Comment by kurzum** [comment]
- [ ] Issue-Tracker is the German writing with `-`. I would report "Report Issues"
- [ ] Could we add a `target=_blank` to all external websites?

**Comment by holycrab13** [comment]
Done for all external links
