### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#58]
Read about the new DBpedia FlexiFusion (the first application built on the Databus): https://svn.aksw.org/papers/2019/ISWC_FlexiFusion/public.pdf

**Comment by holycrab13** [comment]
Done

**Comment by kurzum** [comment]
I think we can link to this as well: http://dev.dbpedia.org/Data
So http://dev.dbpedia.org/Data is an example of how to download DBpedia and the paper is an example application (workflow).

**Comment by holycrab13** [comment]
Done
