### ISSUE TITLE
frontpage latest uploads

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#60]
do it more like maven, e.g. publisher logo, label comment, proper links

**Comment by holycrab13** [comment]
No publisher logo available yet, label and links have been corrected

**Comment by kurzum** [comment]
I think it would nice to have a function to make the dates look like 
March 13, 2019 - 8 am (3 days ago)

**Comment by holycrab13** [comment]
Used a js library to format dates in twitter style
