### ISSUE TITLE
hard to make query at the moment

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#64]
Hi Jan, I was trying to make the following query:

```
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
prefix dataid-cv: <http://dataid.dbpedia.org/ns/cv#> 


# Get all files
SELECT DISTINCT ?file ?lang WHERE {
	?dataset dataid:artifact <https://databus.dbpedia.org/dbpedia/generic/page> .
	?dataset dct:hasVersion '2018.12.14'^^<http://www.w3.org/2001/XMLSchema#string> .
	?dataset dcat:distribution ?distribution .
	?distribution dataid-cv:lang ?lang .
	?distribution dataid:contentVariant 'ids'^^<http://www.w3.org/2001/XMLSchema#string> .  
	?distribution dcat:downloadURL ?file .
}
```

but it was hard, because:
on https://databus.dbpedia.org/dbpedia/generic/page

- [x] `prefix dataid-cv: <http://dataid.dbpedia.org/ns/cv#> ` was missing
- [ ] content variant field was not separated by dimensions
- [x] textfield was not editable, so I had to add to collection first and edit there
- [x] dataid link is shown on artifact page, but not on version page

**Comment by holycrab13** [comment]
Textfield as "not editable" is intended behaviour, only filters can be used on the artifact and version page. In order to make this behaviour more clear, a rework of the query section is needed.

**Comment by holycrab13** [comment]
Added dataid-cv as a default prefix of the query builder

**Comment by holycrab13** [comment]
Added dataid-link to the version page

**Comment by kurzum** [comment]
ok, then we will leave it non-editable.
