### ISSUE TITLE
Collection URL query "too long" for virtuoso ... as GET

### ISSUE THREAD

**Issue by redskate** [dbpedia/databus-maven-plugin#76]
Very nice idea to build SPARQL collections.
Very nice idea to store them as JSON and to paste them to clipboard.
Unfortunately the pasted SPARQL code is just a UNION of all the queries. 
As long as you have 2 or 3 queries this will suit well.
Considering a quite complete DBPedia collection, this results in a UNION expression which is ***NOT*** executable in the provided (thanks) virtuoso SPARQL endpoint. 

Possible sulutions here:
-) rephrase the all-in-one resulting query - do not use UNION on each (sub) query but take the values in OR conjuncions
-) implement a ***POST*** to the provided virtuoso SPARQL endpoint

I know virtuoso's world best subquery operational 
[toolongquery.txt](https://github.com/dbpedia/databus-maven-plugin/files/3342740/toolongquery.txt)
semantics won't allow to easily query all in one (that is why you decided to split at SPARQL level ...) -

**Comment by kurzum** [comment]
POST is already enabled
```
curl -X POST "https://databus.dbpedia.org/repo/sparql" -d "query=select+d3FConcept+where+{[]+a+%3FConcept}+LIMIT+100"
```

**Comment by kurzum** [comment]
```
curl -X POST "https://databus.dbpedia.org/repo/sparql" --data-urlencodtoolongquery.txt"
```
seems to work @redskate can you check?

In principle, we know that the current state is not perfect, but on the other hand it is kind of working already. 
So the solutions we have here are:
1. POST, which already works
2. Users can write shorter queries for themselves, it might take an hour, but then they will work for a long time over the next releases
3. in development, but kind of tricky: we will have some syntax folding for Linked Data URLs, i.e. you can query the files with a url:
- `https://databus.dbpedia.org/dbpedia/mappings/geo-coordinates/LATEST/?lang=it`  
4. other means, probably an SQL interface or a SOLR index

**Comment by kurzum** [comment]
Here is the result
[result.txt](https://github.com/dbpedia/databus-maven-plugin/files/3343986/result.txt)

**Comment by redskate** [comment]
Hi Sebastian

yes - confirmed - it works that way.
Would be nice if this could be integrated directly into the maven plugin - I think this will be on your road map.

Thank you !
