### ISSUE TITLE
rearrange and write new DataIds for generic release

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#8]
referring to http://akswnc7.informatik.uni-leipzig.de/data/dbpedia/2018-04/raw/

goals:
* dataids in folder
* rss feed, when marvin is finished

**Comment by Termilion** [comment]
- [x] dataids: http://akswnc7.informatik.uni-leipzig.de/data/dbpedia/2018-04/bundle/
- [ ]  rss feed

**Comment by kurzum** [comment]
@Termilion I would probably close this. 
https://github.com/dbpedia/databus-shared-lib/blob/master/src/main/scala/org/dbpedia/databus/shared/rdf/vocab/RDFNamespace.scala  
and 
https://github.com/dbpedia/databus-shared-lib/blob/master/src/main/scala/org/dbpedia/databus/shared/rdf/vocab/package.scala

seem to take care of the dataid inclusion in the code.....
