### ISSUE TITLE
improve labels and docu

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#82]
Highest: 
- [x] add `dataid:groupdocu` under `dct:description`
Explanation: I changed the metadata from dct:description "$artifact.md\n\n#$documentationFromPom" into two separate properties:
```
dct:description "$artifact.md"
dataid:groupdocu "$documentationFromPom"
```
They still belong together, but it was hard to handle once merged... They can be separated by a very thin line. Both are markdown. 

Tasks:

- [x]  sebastian: add group label and comment to the store (will load from github)
- [ ] jan, once this is done display them
- [x] sebastian: write some policy lines, i.e. no publisher. group or "dataset" in labels
- [ ] jan: publisher/group in header above artifact/version label
- [x] remove all big <hx> headlines above the docu, so it will never conflict with `#` in the docu string. Add something small/dezent to indicate what it is. Could also be `dc:description` or dataid:groupdocu so users know that this is in the RDF metadata. 
- [ ] @JJ-Author , @kurzum improve https://github.com/dbpedia/databus-content/blob/master/group_labels_comments.ttl and docu in general

**Comment by kurzum** [comment]
https://github.com/dbpedia/databus-maven-plugin/wiki/User-Manual-v1.3#documentation-build-process

**Comment by holycrab13** [comment]
now rendering group label and description (data is incomplete)
added breadcrumbs to header
removed headlines above the docu

**Comment by kurzum** [comment]
Testing:
```
<https://databus.dbpedia.org/dbpedia/mappings> rdfs:label "Wikipedia Extraction using MappingExtractor" .
```
is in https://github.com/dbpedia/databus-content/blob/master/group_labels_comments.ttl#L18

but not in store, will check

**Comment by kurzum** [comment]
Labels were not loaded, my mistake, I guess, I fixed it:
```

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *  WHERE {
  <https://databus.dbpedia.org/dbpedia/mappings> rdfs:label ?l .
  <https://databus.dbpedia.org/dbpedia/mappings> rdfs:comment ?c
} 
```

**Comment by kurzum** [comment]
testing: 

- https://databus.dbpedia.org/dbpedia/mappings/
=> shown, ok
- https://databus.dbpedia.org/dbpedia/mappings/instance-types/2019.08.01
=> NOT visible, display label either in header or table, the info is quite necessary for context, i.e. `where am I?` to understand `what am I looking at?`
- https://databus.dbpedia.org/dbpedia/mappings/instance-types
=> not there, but optional
