### ISSUE TITLE
implement view of mods

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#87]
working on https://github.com/dbpedia/databus-mods/

@holycrab13:
Let me give it some thought and make a plan on how to integrate mods. I also might change the vocab a bit...

**Comment by kurzum** [comment]
So here is the easiest solution, I could think of: 
1. on version page, e.g. https://databus.dbpedia.org/dbpedia/mappings/mappingbased-literals/2018.12.01
2. execute sparql query below
3. if empty do nothing
4. if not empty, add a section Mods (collapsible), that shows the table {?file, ?results}
Note that:
a) results is a string, depending on how many mods there are several will be shown, separated by ','
b) the query works currently. Details might change, but I will ping you.  

![Screenshot from 2019-08-22 15-53-37](https://user-images.githubusercontent.com/900758/63520476-16cbd700-c4f5-11e9-919a-275993083310.png)



```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataiddebug: <http://dataid.dbpedia.org/ns/debug.ttl#>
PREFIX dcat:   <http://www.w3.org/ns/dcat#>

# query all files and their mod results
# group_concat see: https://stackoverflow.com/questions/18212697/aggregating-results-from-sparql-query
SELECT ?file (group_concat(?result;separator=",") as ?results)  WHERE {
  ?dataset dataid:version <https://databus.dbpedia.org/dbpedia/mappings/mappingbased-literals/2018.12.01> .
  ?singlefile dataid:isDistributionOf ?dataset .
  ?singlefile dataid:file ?file .
  
  #?property rdfs:subPropertyOf prov:wasDerivedFrom . 
  #?result ?property ?file .
  ?resultsvg <http://dataid.dbpedia.org/ns/mod.ttl#svgDerivedFrom> ?file .
  ?resultstat <http://dataid.dbpedia.org/ns/mod.ttl#statisticsDerivedFrom> ?file .
  # from the same activity
  ?activity prov:generated ?resultsvg .
  ?activity prov:generated ?resultstat .
  # transform to image link
  # <img src="smiley.gif" alt="Smiley face" height="42" width="42"> 
  BIND (concat("<a href=\"",?resultstat, "\"> <img src=\"",?resultsvg,"\"></a>" ) AS ?result )
  # optionally getting label of the mod
  # ?activity prov:generated ?result .
  # ?activity a ?mod .
     
} 
Group by ?file 
```

**Comment by kurzum** [comment]
@holycrab13 I changed two lines in the query and marked them with UPDATE

**Comment by holycrab13** [comment]
added mod view table (preview and expandable)
