### ISSUE TITLE
declare public beta on databus website

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#88]
There was some confusion about the databus. 
Maybe it is a good idea to declare somewhere that it is a `public beta`, or `under development`. Maybe at one of the two places ??: 
![Screenshot from 2019-08-22 16-46-29](https://user-images.githubusercontent.com/900758/63524597-95784280-c4fc-11e9-8faa-0f2dad4fecb3.png)

Goals are:
* people have clearer expectations
* they are more inclined to provide feedback

**Comment by holycrab13** [comment]
added to header
