### ISSUE TITLE
duplicated entries in faceted browser view due to multiple content-variants per aritifact

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#90]
this is a problem of the sparql query (returns cross product for content variants)
you need probably unique the lines as well as use a group_concat or something to join the content variants

![image](https://user-images.githubusercontent.com/2630603/63626686-94cad380-c604-11e9-9119-be7ecaf2f5cc.png)

![image](https://user-images.githubusercontent.com/2630603/63626751-bd52cd80-c604-11e9-9bb8-14ea4c6dbdbc.png)

**Comment by holycrab13** [comment]
possible fix, needs re-evaluation.

**Comment by holycrab13** [comment]
modifed query to group_by over variant
