### ISSUE TITLE
dimension label is not shown for artifact

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#98]
for https://databus.dbpedia.org/jj-author/dnb/authorities/2019.06.13 the dimension label ("type") is not shown in the faceted browser

**Comment by holycrab13** [comment]
Added more labels to the list of known labels. Added a auto-generated label for unkown labels.

**Comment by holycrab13** [comment]
Please verify and close if possible.

**Comment by JJ-Author** [comment]
tested with https://databus.dbpedia.org/ontologies/zbw.eu/namespaces--zbw-extensions--zbw-extensions--rdf/ and it looks great.
